name: Generate JSON

on:
  push:
     branches: ["main"]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node create-json.js  # Certifique-se de que o seu script esteja na raiz do repositório

      - name: Commit JSON file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update portfolios.json" || true
          git push
