name: Generate Portfolios JSON

on:
  push:
    branches: ["main"]
    paths:
      - 'portfolios/*.md' # Define o padrão para monitorar os arquivos .md

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate JSON
        run: node create-json.js
